/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.gruposistemasdistribuidos.practicasd2.gui;

import com.flickr4java.flickr.FlickrException;
import com.flickr4java.flickr.RequestContext;
import es.gruposistemasdistribuidos.practicasd2.src.MetaData;
import es.gruposistemasdistribuidos.practicasd2.src.Sesion;
import java.awt.Color;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author S.Valeror
 */
public class PracticaSD2GUI extends javax.swing.JFrame {

    private Sesion sesion;
    private File carpeta;

    /**
     * Creates new form practiaSD2GUI
     */
    public PracticaSD2GUI() {

        sesion = new Sesion();

        initComponents();
        jLayeredPaneAlbum.setVisible(false);
        jLayeredPaneOpcional.setVisible(false);
        jLayeredPaneGrupos.setVisible(false);
        jPanelSubSubir.setVisible(true);
        /*if (!(sesion.isPermiso())) {
         for (Component c : jPanelSubSubir.getComponents()) {
         c.setEnabled(false);
         }
         } */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupPrivacidad = new javax.swing.ButtonGroup();
        buttonGroupSeguridad = new javax.swing.ButtonGroup();
        buttonGroupAlbum = new javax.swing.ButtonGroup();
        buttonGroupGrupos = new javax.swing.ButtonGroup();
        buttonGroupLicencia = new javax.swing.ButtonGroup();
        buttonGroupVisibilidad = new javax.swing.ButtonGroup();
        fileChooserCarpetas = new javax.swing.JFileChooser();
        jLayeredPaneOpcional = new javax.swing.JLayeredPane();
        jPanelOpcional = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelAgregarTitulo = new javax.swing.JLabel();
        jTextFieldAgregarTitulo = new javax.swing.JTextField();
        jLabelPreguntaModificar = new javax.swing.JLabel();
        jLabelTipoContenido = new javax.swing.JLabel();
        jLabelPreguntaMotificar2 = new javax.swing.JLabel();
        jLabelAgregarDescripcion = new javax.swing.JLabel();
        jTextFieldAgregarDescripcion = new javax.swing.JTextField();
        jLabelAgregarEtiquetas = new javax.swing.JLabel();
        jTextFieldAgregarEtiquetas = new javax.swing.JTextField();
        jLabelAgregarPersonas = new javax.swing.JLabel();
        jTextFieldAgregarPersonas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jRadioButtonPublicDomainWork = new javax.swing.JRadioButton();
        jRadioButtonPublicDomainDedication = new javax.swing.JRadioButton();
        jRadioButtonNoComercialCompartir = new javax.swing.JRadioButton();
        jRadioButtonNoComercialCreative = new javax.swing.JRadioButton();
        jRadioButtonCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonAtribucionCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonCompartirCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonNoDerivada = new javax.swing.JRadioButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelVisibilidad = new javax.swing.JLabel();
        jRadioButtonPrivada = new javax.swing.JRadioButton();
        jRadioButtonPublica = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLayeredPaneSubir = new javax.swing.JLayeredPane();
        jPanelSubir = new javax.swing.JPanel();
        jPanelSubSubir = new javax.swing.JPanel();
        jLabelPrivacidadElegida = new javax.swing.JLabel();
        jCheckBoxAmigos = new javax.swing.JCheckBox();
        jButtonSubir = new javax.swing.JButton();
        jLabelRuta = new javax.swing.JLabel();
        jRadioButtonSegura = new javax.swing.JRadioButton();
        jLabelSeguridad = new javax.swing.JLabel();
        jButtonOpcionales = new javax.swing.JButton();
        jRadioButtonCaptura = new javax.swing.JRadioButton();
        jRadioButtonFoto = new javax.swing.JRadioButton();
        jRadioButtonPrivado = new javax.swing.JRadioButton();
        jRadioButtonPublico = new javax.swing.JRadioButton();
        jLabelPrivacidad = new javax.swing.JLabel();
        jRadioButtonRestringida = new javax.swing.JRadioButton();
        jLabelTipo = new javax.swing.JLabel();
        jCheckBoxFamiliares = new javax.swing.JCheckBox();
        jRadioButtonArte = new javax.swing.JRadioButton();
        jRadioButtonModerada = new javax.swing.JRadioButton();
        jButtonElegir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLayeredPaneProgressBar = new javax.swing.JLayeredPane();
        jPanelProgressBar = new javax.swing.JPanel();
        jProgressBarSubiendo = new javax.swing.JProgressBar();
        jLabelProgreso = new javax.swing.JLabel();
        jLabelProgresoN1 = new javax.swing.JLabel();
        jLabelProgreso2 = new javax.swing.JLabel();
        jLabelProgresoN2 = new javax.swing.JLabel();
        jLabelProgreso3 = new javax.swing.JLabel();
        jLayeredPaneAlbum = new javax.swing.JLayeredPane();
        jPanelAlbum = new javax.swing.JPanel();
        jLabelTituloAlbum = new javax.swing.JLabel();
        jLabelPreguntaAlbum = new javax.swing.JLabel();
        jLabelTipoContenidoAlbum = new javax.swing.JLabel();
        jLabelPreguntaAlbum2 = new javax.swing.JLabel();
        jRadioButtonSiAlbum = new javax.swing.JRadioButton();
        jRadioButtonNoAlbum = new javax.swing.JRadioButton();
        jLabelNombreAlbum = new javax.swing.JLabel();
        jTextFieldTituloAlbum = new javax.swing.JTextField();
        jLabelDescripcionAlbum = new javax.swing.JLabel();
        jScrollPaneDescripcionAlbum = new javax.swing.JScrollPane();
        jTextAreaDescripcionAlbum = new javax.swing.JTextArea();
        jButtonContinuar = new javax.swing.JButton();
        jLayeredPaneGrupos = new javax.swing.JLayeredPane();
        jPanelGrupos = new javax.swing.JPanel();
        jLabelTituloGrupos = new javax.swing.JLabel();
        jLabelPreguntaGrupos = new javax.swing.JLabel();
        jLabelTipoContenidoGrupos = new javax.swing.JLabel();
        jLabelPreguntaGrupos2 = new javax.swing.JLabel();
        jRadioButtonSiGrupos = new javax.swing.JRadioButton();
        jRadioButtonNoGrupos = new javax.swing.JRadioButton();
        jScrollPaneGrupos = new javax.swing.JScrollPane();
        jListGrupos = new javax.swing.JList();
        jButtonContinuarGrupos = new javax.swing.JButton();

        fileChooserCarpetas.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        fileChooserCarpetas.setMinimumSize(new java.awt.Dimension(644, 419));
        fileChooserCarpetas.setPreferredSize(new java.awt.Dimension(644, 419));
        fileChooserCarpetas.setVerifyInputWhenFocusTarget(false);
        fileChooserCarpetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserCarpetasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(815, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPaneOpcional.setAlignmentX(0.0F);
        jLayeredPaneOpcional.setAlignmentY(0.0F);
        jLayeredPaneOpcional.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneOpcional.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneOpcional.setOpaque(true);

        jPanelOpcional.setAlignmentX(0.0F);
        jPanelOpcional.setAlignmentY(0.0F);
        jPanelOpcional.setDoubleBuffered(false);
        jPanelOpcional.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelOpcional.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelOpcional.setPreferredSize(new java.awt.Dimension(800, 330));
        jPanelOpcional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitulo1.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");
        jPanelOpcional.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jLabelAgregarTitulo.setText("Agregar Titulo");
        jPanelOpcional.add(jLabelAgregarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 93, -1, -1));

        jTextFieldAgregarTitulo.setToolTipText("Opcional");
        jTextFieldAgregarTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldAgregarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgregarTituloActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jTextFieldAgregarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 90, 249, -1));

        jLabelPreguntaModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaModificar.setText("¿Desea modificar algún dato más? (Se aplicará a todo");
        jPanelOpcional.add(jLabelPreguntaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 47, -1, -1));

        jLabelTipoContenido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenido.setText("tipoContenido");
        jPanelOpcional.add(jLabelTipoContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 47, -1, -1));

        jLabelPreguntaMotificar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaMotificar2.setText(")");
        jPanelOpcional.add(jLabelPreguntaMotificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 47, -1, -1));

        jLabelAgregarDescripcion.setText("Agregar descripción");
        jPanelOpcional.add(jLabelAgregarDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 121, -1, -1));
        jPanelOpcional.add(jTextFieldAgregarDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 121, 247, 38));
        jTextFieldAgregarDescripcion.getAccessibleContext().setAccessibleDescription("Opcional");

        jLabelAgregarEtiquetas.setText("Agregar etiquetas");
        jPanelOpcional.add(jLabelAgregarEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 165, -1, -1));
        jPanelOpcional.add(jTextFieldAgregarEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 165, 247, -1));
        jTextFieldAgregarEtiquetas.getAccessibleContext().setAccessibleDescription("Separar etiquetas con espacios");

        jLabelAgregarPersonas.setText("Agregar personas");
        jPanelOpcional.add(jLabelAgregarPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 199, -1, -1));
        jPanelOpcional.add(jTextFieldAgregarPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 196, 248, -1));
        jTextFieldAgregarPersonas.getAccessibleContext().setAccessibleDescription("Escribir nombre o dirección de correo electrónico");

        jLabel1.setText("Licencias");
        jPanelOpcional.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 70, -1, -1));

        buttonGroupLicencia.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setMnemonic('0');
        jRadioButtonNinguno.setSelected(true);
        jRadioButtonNinguno.setText("Ninguno (Todos los derechos reservados)");
        jRadioButtonNinguno.setActionCommand("0");
        jRadioButtonNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunoActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jRadioButtonNinguno, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 90, -1, -1));

        buttonGroupLicencia.add(jRadioButtonPublicDomainWork);
        jRadioButtonPublicDomainWork.setMnemonic('7');
        jRadioButtonPublicDomainWork.setText("Public Domain Work");
        jRadioButtonPublicDomainWork.setActionCommand("7");
        jPanelOpcional.add(jRadioButtonPublicDomainWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 113, -1, -1));

        buttonGroupLicencia.add(jRadioButtonPublicDomainDedication);
        jRadioButtonPublicDomainDedication.setMnemonic('8');
        jRadioButtonPublicDomainDedication.setText("Public Domain Dedication (CC0)");
        jRadioButtonPublicDomainDedication.setActionCommand("8");
        jRadioButtonPublicDomainDedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPublicDomainDedicationActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jRadioButtonPublicDomainDedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 136, -1, -1));

        buttonGroupLicencia.add(jRadioButtonNoComercialCompartir);
        jRadioButtonNoComercialCompartir.setMnemonic('1');
        jRadioButtonNoComercialCompartir.setText("Atribución-No comercial-Compartir bajo la misma licencia de Creative Commons");
        jRadioButtonNoComercialCompartir.setActionCommand("1");
        jPanelOpcional.add(jRadioButtonNoComercialCompartir, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 159, -1, -1));

        buttonGroupLicencia.add(jRadioButtonNoComercialCreative);
        jRadioButtonNoComercialCreative.setMnemonic('2');
        jRadioButtonNoComercialCreative.setText("Atribución-No comercial de Creative Commons");
        jRadioButtonNoComercialCreative.setActionCommand("2");
        jPanelOpcional.add(jRadioButtonNoComercialCreative, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 182, -1, -1));

        buttonGroupLicencia.add(jRadioButtonCreativeCommons);
        jRadioButtonCreativeCommons.setMnemonic('3');
        jRadioButtonCreativeCommons.setText("Creative Commons Atribución-No Comercial - No Derivs");
        jRadioButtonCreativeCommons.setActionCommand("3");
        jRadioButtonCreativeCommons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreativeCommonsActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jRadioButtonCreativeCommons, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 208, -1, -1));

        buttonGroupLicencia.add(jRadioButtonAtribucionCreativeCommons);
        jRadioButtonAtribucionCreativeCommons.setMnemonic('4');
        jRadioButtonAtribucionCreativeCommons.setText("Atribución de Creative Commons");
        jRadioButtonAtribucionCreativeCommons.setActionCommand("4");
        jPanelOpcional.add(jRadioButtonAtribucionCreativeCommons, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 231, -1, -1));

        buttonGroupLicencia.add(jRadioButtonCompartirCreativeCommons);
        jRadioButtonCompartirCreativeCommons.setMnemonic('5');
        jRadioButtonCompartirCreativeCommons.setText("Atribución-Compartir bajo la misma licencia de Creative Commons");
        jRadioButtonCompartirCreativeCommons.setActionCommand("5");
        jPanelOpcional.add(jRadioButtonCompartirCreativeCommons, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 257, -1, -1));

        buttonGroupLicencia.add(jRadioButtonNoDerivada);
        jRadioButtonNoDerivada.setMnemonic('6');
        jRadioButtonNoDerivada.setText("Atribución-No derivadas de Creative Commons");
        jRadioButtonNoDerivada.setActionCommand("6");
        jPanelOpcional.add(jRadioButtonNoDerivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 280, -1, -1));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 352, 53));

        jLabelVisibilidad.setText("Visibilidad en Búsquedas:");
        jPanelOpcional.add(jLabelVisibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        buttonGroupVisibilidad.add(jRadioButtonPrivada);
        jRadioButtonPrivada.setText("Privada");
        jRadioButtonPrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrivadaActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jRadioButtonPrivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        buttonGroupVisibilidad.add(jRadioButtonPublica);
        jRadioButtonPublica.setSelected(true);
        jRadioButtonPublica.setText("Pública");
        jRadioButtonPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPublicaActionPerformed(evt);
            }
        });
        jPanelOpcional.add(jRadioButtonPublica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        jPanelOpcional.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 110, 40));

        javax.swing.GroupLayout jLayeredPaneOpcionalLayout = new javax.swing.GroupLayout(jLayeredPaneOpcional);
        jLayeredPaneOpcional.setLayout(jLayeredPaneOpcionalLayout);
        jLayeredPaneOpcionalLayout.setHorizontalGroup(
            jLayeredPaneOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOpcionalLayout.createSequentialGroup()
                .addComponent(jPanelOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneOpcionalLayout.setVerticalGroup(
            jLayeredPaneOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOpcionalLayout.createSequentialGroup()
                .addComponent(jPanelOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneOpcional.setLayer(jPanelOpcional, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneSubir.setAlignmentX(0.0F);
        jLayeredPaneSubir.setAlignmentY(0.0F);
        jLayeredPaneSubir.setEnabled(false);
        jLayeredPaneSubir.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneSubir.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneSubir.setOpaque(true);

        jPanelSubir.setAlignmentX(0.0F);
        jPanelSubir.setAlignmentY(0.0F);
        jPanelSubir.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelSubir.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelSubir.setPreferredSize(new java.awt.Dimension(800, 330));
        jPanelSubir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrivacidadElegida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrivacidadElegida.setForeground(java.awt.Color.green);
        jLabelPrivacidadElegida.setText("Visible para todos");

        jCheckBoxAmigos.setText("Tus Amigos");
        jCheckBoxAmigos.setEnabled(false);
        jCheckBoxAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAmigosActionPerformed(evt);
            }
        });
        jCheckBoxAmigos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheckBoxAmigosPropertyChange(evt);
            }
        });

        jButtonSubir.setText("Confirmar y Subir");
        jButtonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirActionPerformed(evt);
            }
        });

        jLabelRuta.setText("Ruta no Elegida");

        buttonGroupSeguridad.add(jRadioButtonSegura);
        jRadioButtonSegura.setMnemonic('1');
        jRadioButtonSegura.setText("Segura");
        jRadioButtonSegura.setActionCommand("1");
        jRadioButtonSegura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeguraActionPerformed(evt);
            }
        });

        jLabelSeguridad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSeguridad.setText("Seguridad");

        jButtonOpcionales.setText("Detalles Opcionales");
        jButtonOpcionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcionalesActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonCaptura);
        jRadioButtonCaptura.setMnemonic('2');
        jRadioButtonCaptura.setText("Captura de Pantalla");
        jRadioButtonCaptura.setActionCommand("2");
        jRadioButtonCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCapturaActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonFoto);
        jRadioButtonFoto.setMnemonic('1');
        jRadioButtonFoto.setSelected(true);
        jRadioButtonFoto.setText("Foto");
        jRadioButtonFoto.setActionCommand("1");
        jRadioButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFotoActionPerformed(evt);
            }
        });

        buttonGroupPrivacidad.add(jRadioButtonPrivado);
        jRadioButtonPrivado.setText("Sólo Tú (privado)");
        jRadioButtonPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrivadoActionPerformed(evt);
            }
        });

        buttonGroupPrivacidad.add(jRadioButtonPublico);
        jRadioButtonPublico.setSelected(true);
        jRadioButtonPublico.setText("Cualquier Persona (público)");
        jRadioButtonPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPublicoActionPerformed(evt);
            }
        });

        jLabelPrivacidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrivacidad.setText("Privacidad");

        buttonGroupSeguridad.add(jRadioButtonRestringida);
        jRadioButtonRestringida.setMnemonic('3');
        jRadioButtonRestringida.setText("Restringida");
        jRadioButtonRestringida.setActionCommand("3");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipo.setText("Tipo de Contenido");

        jCheckBoxFamiliares.setText("Tus Familiares");
        jCheckBoxFamiliares.setEnabled(false);
        jCheckBoxFamiliares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFamiliaresActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonArte);
        jRadioButtonArte.setMnemonic('3');
        jRadioButtonArte.setText("Arte/Ilustracción");
        jRadioButtonArte.setActionCommand("3");

        buttonGroupSeguridad.add(jRadioButtonModerada);
        jRadioButtonModerada.setMnemonic('2');
        jRadioButtonModerada.setSelected(true);
        jRadioButtonModerada.setText("Moderada");
        jRadioButtonModerada.setActionCommand("2");

        jButtonElegir.setText("Elegir Carpeta a Subir");
        jButtonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubSubirLayout = new javax.swing.GroupLayout(jPanelSubSubir);
        jPanelSubSubir.setLayout(jPanelSubSubirLayout);
        jPanelSubSubirLayout.setHorizontalGroup(
            jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPrivacidad))
                    .addComponent(jLabelRuta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabelPrivacidadElegida)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTipo)
                                .addComponent(jRadioButtonArte)
                                .addComponent(jRadioButtonCaptura)
                                .addComponent(jRadioButtonFoto))
                            .addGap(188, 188, 188)
                            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jRadioButtonPrivado))
                                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jCheckBoxAmigos))
                                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jCheckBoxFamiliares))
                                .addComponent(jRadioButtonPublico))
                            .addGap(174, 174, 174)
                            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSeguridad)
                                .addComponent(jRadioButtonSegura)
                                .addComponent(jRadioButtonModerada)
                                .addComponent(jRadioButtonRestringida)))
                        .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jButtonOpcionales, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSubSubirLayout.setVerticalGroup(
            jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrivacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrivacidadElegida)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabelTipo)
                            .addGap(13, 13, 13)
                            .addGroup(jPanelSubSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jRadioButtonArte))
                                .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jRadioButtonCaptura))
                                .addComponent(jRadioButtonFoto)))
                        .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jRadioButtonPrivado)
                            .addGap(3, 3, 3)
                            .addComponent(jCheckBoxAmigos)
                            .addGap(0, 0, 0)
                            .addComponent(jCheckBoxFamiliares)
                            .addGap(3, 3, 3)
                            .addComponent(jRadioButtonPublico))
                        .addGroup(jPanelSubSubirLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabelSeguridad)
                            .addGap(3, 3, 3)
                            .addComponent(jRadioButtonSegura)
                            .addGap(7, 7, 7)
                            .addComponent(jRadioButtonModerada)
                            .addGap(7, 7, 7)
                            .addComponent(jRadioButtonRestringida)))
                    .addGap(5, 5, 5)
                    .addComponent(jButtonOpcionales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jButtonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelSubir.add(jPanelSubSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 290));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitulo.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");
        jPanelSubir.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        javax.swing.GroupLayout jLayeredPaneSubirLayout = new javax.swing.GroupLayout(jLayeredPaneSubir);
        jLayeredPaneSubir.setLayout(jLayeredPaneSubirLayout);
        jLayeredPaneSubirLayout.setHorizontalGroup(
            jLayeredPaneSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPaneSubirLayout.setVerticalGroup(
            jLayeredPaneSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPaneSubir.setLayer(jPanelSubir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneProgressBar.setAlignmentX(0.0F);
        jLayeredPaneProgressBar.setAlignmentY(0.0F);
        jLayeredPaneProgressBar.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneProgressBar.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneProgressBar.setOpaque(true);

        jPanelProgressBar.setAlignmentX(0.0F);
        jPanelProgressBar.setAlignmentY(0.0F);
        jPanelProgressBar.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelProgressBar.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelProgressBar.setPreferredSize(new java.awt.Dimension(800, 330));

        jLabelProgreso.setText("Progreso: ");

        jLabelProgresoN1.setText("n1");

        jLabelProgreso2.setText("ficheros subidos, ");

        jLabelProgresoN2.setText("n2");

        jLabelProgreso3.setText("pendientes");

        javax.swing.GroupLayout jPanelProgressBarLayout = new javax.swing.GroupLayout(jPanelProgressBar);
        jPanelProgressBar.setLayout(jPanelProgressBarLayout);
        jPanelProgressBarLayout.setHorizontalGroup(
            jPanelProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressBarLayout.createSequentialGroup()
                .addGroup(jPanelProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProgressBarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jProgressBarSubiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProgressBarLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabelProgreso)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelProgresoN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProgreso2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProgresoN2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProgreso3)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanelProgressBarLayout.setVerticalGroup(
            jPanelProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressBarLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jProgressBarSubiendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProgreso)
                    .addComponent(jLabelProgresoN1)
                    .addComponent(jLabelProgreso2)
                    .addComponent(jLabelProgresoN2)
                    .addComponent(jLabelProgreso3))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPaneProgressBarLayout = new javax.swing.GroupLayout(jLayeredPaneProgressBar);
        jLayeredPaneProgressBar.setLayout(jLayeredPaneProgressBarLayout);
        jLayeredPaneProgressBarLayout.setHorizontalGroup(
            jLayeredPaneProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneProgressBarLayout.createSequentialGroup()
                .addComponent(jPanelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneProgressBarLayout.setVerticalGroup(
            jLayeredPaneProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneProgressBarLayout.createSequentialGroup()
                .addComponent(jPanelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneProgressBar.setLayer(jPanelProgressBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneAlbum.setAlignmentX(0.0F);
        jLayeredPaneAlbum.setAlignmentY(0.0F);
        jLayeredPaneAlbum.setAutoscrolls(true);
        jLayeredPaneAlbum.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneAlbum.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneAlbum.setOpaque(true);

        jPanelAlbum.setAlignmentX(0.0F);
        jPanelAlbum.setAlignmentY(0.0F);
        jPanelAlbum.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelAlbum.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelAlbum.setPreferredSize(new java.awt.Dimension(800, 330));

        jLabelTituloAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTituloAlbum.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jLabelPreguntaAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaAlbum.setText("¿Desea añadir estas");

        jLabelTipoContenidoAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenidoAlbum.setText("tipoContenido");

        jLabelPreguntaAlbum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaAlbum2.setText("a un album?");

        buttonGroupAlbum.add(jRadioButtonSiAlbum);
        jRadioButtonSiAlbum.setText("Si");
        jRadioButtonSiAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiAlbumActionPerformed(evt);
            }
        });

        buttonGroupAlbum.add(jRadioButtonNoAlbum);
        jRadioButtonNoAlbum.setText("No");

        jLabelNombreAlbum.setText("Título del Album:");

        jTextFieldTituloAlbum.setText("carpetaSeleccionada");

        jLabelDescripcionAlbum.setText("Descripción del Album:");

        jTextAreaDescripcionAlbum.setColumns(20);
        jTextAreaDescripcionAlbum.setRows(5);
        jScrollPaneDescripcionAlbum.setViewportView(jTextAreaDescripcionAlbum);

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlbumLayout = new javax.swing.GroupLayout(jPanelAlbum);
        jPanelAlbum.setLayout(jPanelAlbumLayout);
        jPanelAlbumLayout.setHorizontalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlbumLayout.createSequentialGroup()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAlbumLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jRadioButtonSiAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNoAlbum))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAlbumLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelTituloAlbum)))
                .addGap(24, 196, Short.MAX_VALUE))
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlbumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabelPreguntaAlbum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTipoContenidoAlbum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPreguntaAlbum2))
                            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDescripcionAlbum)
                                    .addComponent(jLabelNombreAlbum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTituloAlbum)
                                    .addComponent(jScrollPaneDescripcionAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAlbumLayout.setVerticalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreguntaAlbum)
                    .addComponent(jLabelTipoContenidoAlbum)
                    .addComponent(jLabelPreguntaAlbum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSiAlbum)
                    .addComponent(jRadioButtonNoAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreAlbum)
                    .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneDescripcionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelDescripcionAlbum)))
                .addGap(18, 18, 18)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneAlbumLayout = new javax.swing.GroupLayout(jLayeredPaneAlbum);
        jLayeredPaneAlbum.setLayout(jLayeredPaneAlbumLayout);
        jLayeredPaneAlbumLayout.setHorizontalGroup(
            jLayeredPaneAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAlbumLayout.createSequentialGroup()
                .addComponent(jPanelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneAlbumLayout.setVerticalGroup(
            jLayeredPaneAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAlbumLayout.createSequentialGroup()
                .addComponent(jPanelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneAlbum.setLayer(jPanelAlbum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneGrupos.setAlignmentX(0.0F);
        jLayeredPaneGrupos.setAlignmentY(0.0F);
        jLayeredPaneGrupos.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneGrupos.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneGrupos.setOpaque(true);

        jPanelGrupos.setAlignmentX(0.0F);
        jPanelGrupos.setAlignmentY(0.0F);
        jPanelGrupos.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelGrupos.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelGrupos.setPreferredSize(new java.awt.Dimension(800, 330));

        jLabelTituloGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTituloGrupos.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jLabelPreguntaGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaGrupos.setText("¿Desea añadir estas");

        jLabelTipoContenidoGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenidoGrupos.setText("tipoContenido");

        jLabelPreguntaGrupos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaGrupos2.setText("a un mural (pool) de un grupo?");

        buttonGroupGrupos.add(jRadioButtonSiGrupos);
        jRadioButtonSiGrupos.setText("Si");
        jRadioButtonSiGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiGruposActionPerformed(evt);
            }
        });

        buttonGroupGrupos.add(jRadioButtonNoGrupos);
        jRadioButtonNoGrupos.setText("No");
        jRadioButtonNoGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoGruposActionPerformed(evt);
            }
        });

        jListGrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneGrupos.setViewportView(jListGrupos);

        jButtonContinuarGrupos.setText("Continuar");

        javax.swing.GroupLayout jPanelGruposLayout = new javax.swing.GroupLayout(jPanelGrupos);
        jPanelGrupos.setLayout(jPanelGruposLayout);
        jPanelGruposLayout.setHorizontalGroup(
            jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGruposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSiGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNoGrupos)
                .addGap(356, 356, 356))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGruposLayout.createSequentialGroup()
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGruposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonContinuarGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelGruposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneGrupos))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGruposLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelGruposLayout.createSequentialGroup()
                                .addComponent(jLabelPreguntaGrupos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTipoContenidoGrupos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPreguntaGrupos2))
                            .addComponent(jLabelTituloGrupos))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanelGruposLayout.setVerticalGroup(
            jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloGrupos)
                .addGap(18, 18, 18)
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreguntaGrupos)
                    .addComponent(jLabelTipoContenidoGrupos)
                    .addComponent(jLabelPreguntaGrupos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSiGrupos)
                    .addComponent(jRadioButtonNoGrupos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinuarGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneGruposLayout = new javax.swing.GroupLayout(jLayeredPaneGrupos);
        jLayeredPaneGrupos.setLayout(jLayeredPaneGruposLayout);
        jLayeredPaneGruposLayout.setHorizontalGroup(
            jLayeredPaneGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneGruposLayout.createSequentialGroup()
                .addComponent(jPanelGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );
        jLayeredPaneGruposLayout.setVerticalGroup(
            jLayeredPaneGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneGruposLayout.createSequentialGroup()
                .addComponent(jPanelGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        jLayeredPaneGrupos.setLayer(jPanelGrupos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirActionPerformed
        int returnVal = fileChooserCarpetas.showOpenDialog(jPanelSubir);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            carpeta = fileChooserCarpetas.getSelectedFile();
            jLabelRuta.setText(carpeta.getAbsolutePath());
        } else {

        }
    }//GEN-LAST:event_jButtonElegirActionPerformed

    private void jRadioButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFotoActionPerformed

    private void jRadioButtonSeguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSeguraActionPerformed

    private void jButtonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirActionPerformed
        // jLayeredPaneSubir.setVisible(false);
        // jLayeredPaneProgressBar.setVisible(true);

        String seguridad = String.valueOf(buttonGroupSeguridad.getSelection().getActionCommand());
        String tipoContenido = String.valueOf(buttonGroupTipo.getSelection().getActionCommand());
        int privacidad;
        if (jRadioButtonPrivado.isSelected()) {
            privacidad = 5;
        } else {
            privacidad = 1;
            if (jCheckBoxAmigos.isSelected() && jCheckBoxFamiliares.isSelected()) {
                privacidad = 4;
            } else if (jCheckBoxFamiliares.isSelected()) {
                privacidad = 3;
            } else if (jCheckBoxAmigos.isSelected()) {
                privacidad = 2;
            }
        }
        MetaData metaData = new MetaData(carpeta, seguridad, tipoContenido, privacidad);
        if (!jTextFieldAgregarTitulo.getText().isEmpty()) {
            metaData.setTitulo(jTextFieldAgregarTitulo.getText());
        }
        if (!jTextFieldAgregarDescripcion.getText().isEmpty()) {
            metaData.setDescripcion(jTextFieldAgregarDescripcion.getText());
        }
        if (!jTextFieldAgregarEtiquetas.getText().isEmpty()) {
            String[] etiquetas = jTextFieldAgregarEtiquetas.getText().split(" ");
            for (String s : etiquetas) {
                metaData.getEtiquetas().add(s);
            }
        }
        if (!jTextFieldAgregarPersonas.getText().isEmpty()) {
            String[] personas = jTextFieldAgregarPersonas.getText().split(" ");
            for (String s : personas) {
                metaData.getPersonas().add(s);
            }
        }

        metaData.setLicencia(Integer.valueOf(buttonGroupLicencia.getSelection().getActionCommand()));

        try {
            sesion.uploadFolder(metaData);
        } catch (FlickrException ex) {
            Logger.getLogger(PracticaSD2GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSubirActionPerformed

    private void jRadioButtonSiAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSiAlbumActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jTextFieldAgregarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgregarTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgregarTituloActionPerformed

    private void jRadioButtonPublicDomainDedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPublicDomainDedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPublicDomainDedicationActionPerformed

    private void jRadioButtonCreativeCommonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreativeCommonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCreativeCommonsActionPerformed

    private void jButtonOpcionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcionalesActionPerformed
        jLayeredPaneSubir.setVisible(false);
        jLayeredPaneOpcional.setVisible(true);
    }//GEN-LAST:event_jButtonOpcionalesActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        jLayeredPaneOpcional.setVisible(false);
        jLayeredPaneSubir.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jRadioButtonPrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPrivadaActionPerformed

    private void jRadioButtonPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPublicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPublicaActionPerformed

    private void fileChooserCarpetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserCarpetasActionPerformed

    }//GEN-LAST:event_fileChooserCarpetasActionPerformed

    private void jRadioButtonPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrivadoActionPerformed
        jLabelPrivacidadElegida.setText("Sólo visible para ti");
        jLabelPrivacidadElegida.setForeground(Color.RED);
        jCheckBoxAmigos.setSelected(false);
        jCheckBoxFamiliares.setSelected(false);
        jCheckBoxAmigos.setEnabled(true);
        jCheckBoxFamiliares.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonPrivadoActionPerformed

    private void jRadioButtonPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPublicoActionPerformed
        jLabelPrivacidadElegida.setText("Visible para todos");
        jLabelPrivacidadElegida.setForeground(Color.GREEN);
        jCheckBoxAmigos.setSelected(false);
        jCheckBoxFamiliares.setSelected(false);
        jCheckBoxAmigos.setEnabled(false);
        jCheckBoxFamiliares.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonPublicoActionPerformed

    private void jCheckBoxAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAmigosActionPerformed
        jLabelPrivacidadElegida.setForeground(Color.YELLOW);
        if (jCheckBoxAmigos.isSelected() && jCheckBoxFamiliares.isSelected()) {
            jLabelPrivacidadElegida.setText("Visible para tus amigos y tus familiares.");
        } else {
            if (jCheckBoxAmigos.isSelected() && !jCheckBoxFamiliares.isSelected()) {
                jLabelPrivacidadElegida.setText("Visible para tus amigos.");
            } else if (jCheckBoxFamiliares.isSelected() && !jCheckBoxAmigos.isSelected()) {
                jLabelPrivacidadElegida.setText("Visible para tus familiares.");

            } else {
                jRadioButtonPrivadoActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jCheckBoxAmigosActionPerformed

    private void jCheckBoxFamiliaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFamiliaresActionPerformed
        jLabelPrivacidadElegida.setForeground(Color.YELLOW);
        if (jCheckBoxAmigos.isSelected() && jCheckBoxFamiliares.isSelected()) {
            jLabelPrivacidadElegida.setText("Visible para tus amigos y tus familiares.");
        } else {
            if (jCheckBoxFamiliares.isSelected() && !jCheckBoxAmigos.isSelected()) {
                jLabelPrivacidadElegida.setText("Visible para tus familiares.");
            } else if (jCheckBoxAmigos.isSelected() && !jCheckBoxFamiliares.isSelected()) {
                jLabelPrivacidadElegida.setText("Visible para tus amigos.");
            } else {
                jRadioButtonPrivadoActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jCheckBoxFamiliaresActionPerformed

    private void jCheckBoxAmigosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheckBoxAmigosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAmigosPropertyChange

    private void jRadioButtonSiGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSiGruposActionPerformed

    private void jRadioButtonNoGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNoGruposActionPerformed

    private void jRadioButtonCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCapturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCapturaActionPerformed

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaSD2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaSD2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaSD2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaSD2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaSD2GUI().setVisible(true);
            }
        });
    }

    // <editor-fold desc="generated code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlbum;
    private javax.swing.ButtonGroup buttonGroupGrupos;
    private javax.swing.ButtonGroup buttonGroupLicencia;
    private javax.swing.ButtonGroup buttonGroupPrivacidad;
    private javax.swing.ButtonGroup buttonGroupSeguridad;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.ButtonGroup buttonGroupVisibilidad;
    private javax.swing.JFileChooser fileChooserCarpetas;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonContinuarGrupos;
    private javax.swing.JButton jButtonElegir;
    private javax.swing.JButton jButtonOpcionales;
    private javax.swing.JButton jButtonSubir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JCheckBox jCheckBoxAmigos;
    private javax.swing.JCheckBox jCheckBoxFamiliares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgregarDescripcion;
    private javax.swing.JLabel jLabelAgregarEtiquetas;
    private javax.swing.JLabel jLabelAgregarPersonas;
    private javax.swing.JLabel jLabelAgregarTitulo;
    private javax.swing.JLabel jLabelDescripcionAlbum;
    private javax.swing.JLabel jLabelNombreAlbum;
    private javax.swing.JLabel jLabelPreguntaAlbum;
    private javax.swing.JLabel jLabelPreguntaAlbum2;
    private javax.swing.JLabel jLabelPreguntaGrupos;
    private javax.swing.JLabel jLabelPreguntaGrupos2;
    private javax.swing.JLabel jLabelPreguntaModificar;
    private javax.swing.JLabel jLabelPreguntaMotificar2;
    private javax.swing.JLabel jLabelPrivacidad;
    private javax.swing.JLabel jLabelPrivacidadElegida;
    private javax.swing.JLabel jLabelProgreso;
    private javax.swing.JLabel jLabelProgreso2;
    private javax.swing.JLabel jLabelProgreso3;
    private javax.swing.JLabel jLabelProgresoN1;
    private javax.swing.JLabel jLabelProgresoN2;
    private javax.swing.JLabel jLabelRuta;
    private javax.swing.JLabel jLabelSeguridad;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoContenido;
    private javax.swing.JLabel jLabelTipoContenidoAlbum;
    private javax.swing.JLabel jLabelTipoContenidoGrupos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTituloAlbum;
    private javax.swing.JLabel jLabelTituloGrupos;
    private javax.swing.JLabel jLabelVisibilidad;
    private javax.swing.JLayeredPane jLayeredPaneAlbum;
    private javax.swing.JLayeredPane jLayeredPaneGrupos;
    private javax.swing.JLayeredPane jLayeredPaneOpcional;
    private javax.swing.JLayeredPane jLayeredPaneProgressBar;
    private javax.swing.JLayeredPane jLayeredPaneSubir;
    private javax.swing.JList jListGrupos;
    private javax.swing.JPanel jPanelAlbum;
    private javax.swing.JPanel jPanelGrupos;
    private javax.swing.JPanel jPanelOpcional;
    private javax.swing.JPanel jPanelProgressBar;
    private javax.swing.JPanel jPanelSubSubir;
    private javax.swing.JPanel jPanelSubir;
    private javax.swing.JProgressBar jProgressBarSubiendo;
    private javax.swing.JRadioButton jRadioButtonArte;
    private javax.swing.JRadioButton jRadioButtonAtribucionCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonCaptura;
    private javax.swing.JRadioButton jRadioButtonCompartirCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonFoto;
    private javax.swing.JRadioButton jRadioButtonModerada;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonNoAlbum;
    private javax.swing.JRadioButton jRadioButtonNoComercialCompartir;
    private javax.swing.JRadioButton jRadioButtonNoComercialCreative;
    private javax.swing.JRadioButton jRadioButtonNoDerivada;
    private javax.swing.JRadioButton jRadioButtonNoGrupos;
    private javax.swing.JRadioButton jRadioButtonPrivada;
    private javax.swing.JRadioButton jRadioButtonPrivado;
    private javax.swing.JRadioButton jRadioButtonPublicDomainDedication;
    private javax.swing.JRadioButton jRadioButtonPublicDomainWork;
    private javax.swing.JRadioButton jRadioButtonPublica;
    private javax.swing.JRadioButton jRadioButtonPublico;
    private javax.swing.JRadioButton jRadioButtonRestringida;
    private javax.swing.JRadioButton jRadioButtonSegura;
    private javax.swing.JRadioButton jRadioButtonSiAlbum;
    private javax.swing.JRadioButton jRadioButtonSiGrupos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDescripcionAlbum;
    private javax.swing.JScrollPane jScrollPaneGrupos;
    private javax.swing.JTextArea jTextAreaDescripcionAlbum;
    private javax.swing.JTextField jTextFieldAgregarDescripcion;
    private javax.swing.JTextField jTextFieldAgregarEtiquetas;
    private javax.swing.JTextField jTextFieldAgregarPersonas;
    private javax.swing.JTextField jTextFieldAgregarTitulo;
    private javax.swing.JTextField jTextFieldTituloAlbum;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
