/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.gruposistemasdistribuidos.practicasd2.gui;

/**
 *
 * @author S.Valeror
 */
public class practiaSD2GUI extends javax.swing.JFrame {

    /**
     * Creates new form practiaSD2GUI
     */
    public practiaSD2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupPrivacidad = new javax.swing.ButtonGroup();
        buttonGroupPrivacidadPrivado = new javax.swing.ButtonGroup();
        buttonGroupSeguridad = new javax.swing.ButtonGroup();
        buttonGroupAlbum = new javax.swing.ButtonGroup();
        buttonGroupGrupos = new javax.swing.ButtonGroup();
        buttonGroupLicencia = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLayeredPaneOpcional = new javax.swing.JLayeredPane();
        jPanelOpcional = new javax.swing.JPanel();
        jButtonPermisos1 = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        jButtonApi1 = new javax.swing.JButton();
        jLabelAgregarTitulo = new javax.swing.JLabel();
        jTextFieldAgregarTitulo = new javax.swing.JTextField();
        jLabelPreguntaModificar = new javax.swing.JLabel();
        jLabelTipoContenido = new javax.swing.JLabel();
        jLabelPreguntaMotificar2 = new javax.swing.JLabel();
        jLabelAgregarDescripcion = new javax.swing.JLabel();
        jTextFieldAgregarDescripcion = new javax.swing.JTextField();
        jLabelAgregarEtiquetas = new javax.swing.JLabel();
        jTextFieldAgregarEtiquetas = new javax.swing.JTextField();
        jLabelAgregarPersonas = new javax.swing.JLabel();
        jTextFieldAgregarPersonas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jRadioButtonPublicDomainWork = new javax.swing.JRadioButton();
        jRadioButtonPublicDomainDedication = new javax.swing.JRadioButton();
        jRadioButtonNoComercialCompartir = new javax.swing.JRadioButton();
        jRadioButtonNoComercialCreative = new javax.swing.JRadioButton();
        jRadioButtonCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonAtribucionCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonCompartirCreativeCommons = new javax.swing.JRadioButton();
        jRadioButtonNoDerivada = new javax.swing.JRadioButton();
        jButtonFinalizar = new javax.swing.JButton();
        jLayeredPaneAlbum = new javax.swing.JLayeredPane();
        jPanelAlbum = new javax.swing.JPanel();
        jLabelTituloAlbum = new javax.swing.JLabel();
        jButtonApiAlbum = new javax.swing.JButton();
        jButtonPermisosAlbum = new javax.swing.JButton();
        jLabelPreguntaAlbum = new javax.swing.JLabel();
        jLabelTipoContenidoAlbum = new javax.swing.JLabel();
        jLabelPreguntaAlbum2 = new javax.swing.JLabel();
        jRadioButtonSiAlbum = new javax.swing.JRadioButton();
        jRadioButtonNoAlbum = new javax.swing.JRadioButton();
        jLabelNombreAlbum = new javax.swing.JLabel();
        jTextFieldTituloAlbum = new javax.swing.JTextField();
        jLabelDescripcionAlbum = new javax.swing.JLabel();
        jScrollPaneDescripcionAlbum = new javax.swing.JScrollPane();
        jTextAreaDescripcionAlbum = new javax.swing.JTextArea();
        jButtonContinuar = new javax.swing.JButton();
        jLayeredPaneGrupos = new javax.swing.JLayeredPane();
        jPanelGrupos = new javax.swing.JPanel();
        jButtonApiGrupos = new javax.swing.JButton();
        jButtonPermisosGrupos = new javax.swing.JButton();
        jLabelTituloGrupos = new javax.swing.JLabel();
        jLabelPreguntaGrupos = new javax.swing.JLabel();
        jLabelTipoContenidoGrupos = new javax.swing.JLabel();
        jLabelPreguntaGrupos2 = new javax.swing.JLabel();
        jRadioButtonSiGrupos = new javax.swing.JRadioButton();
        jRadioButtonNoGrupos = new javax.swing.JRadioButton();
        jScrollPaneGrupos = new javax.swing.JScrollPane();
        jListGrupos = new javax.swing.JList();
        jButtonContinuarGrupos = new javax.swing.JButton();
        jLayeredPaneSubir = new javax.swing.JLayeredPane();
        jPanelSubir = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonApi = new javax.swing.JButton();
        jButtonPermisos = new javax.swing.JButton();
        jButtonElegir = new javax.swing.JButton();
        jLabelRuta = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jRadioButtonFoto = new javax.swing.JRadioButton();
        jRadioButtonCaptura = new javax.swing.JRadioButton();
        jRadioButtonArte = new javax.swing.JRadioButton();
        jLabelPrivacidad = new javax.swing.JLabel();
        jLabelPrivacidadElegida = new javax.swing.JLabel();
        jRadioButtonPrivado = new javax.swing.JRadioButton();
        jCheckBoxAmigos = new javax.swing.JCheckBox();
        jCheckBoxFamiliares = new javax.swing.JCheckBox();
        jRadioButtonPublico = new javax.swing.JRadioButton();
        jLabelSeguridad = new javax.swing.JLabel();
        jRadioButtonSegura = new javax.swing.JRadioButton();
        jRadioButtonModerada = new javax.swing.JRadioButton();
        jRadioButtonRestringida = new javax.swing.JRadioButton();
        jButtonSubir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 330));
        setMinimumSize(new java.awt.Dimension(800, 330));
        setPreferredSize(new java.awt.Dimension(800, 330));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPaneOpcional.setAlignmentX(0.0F);
        jLayeredPaneOpcional.setAlignmentY(0.0F);
        jLayeredPaneOpcional.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneOpcional.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneOpcional.setOpaque(true);

        jPanelOpcional.setAlignmentX(0.0F);
        jPanelOpcional.setAlignmentY(0.0F);
        jPanelOpcional.setDoubleBuffered(false);
        jPanelOpcional.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelOpcional.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelOpcional.setPreferredSize(new java.awt.Dimension(800, 330));

        jButtonPermisos1.setText("Permisos");
        jButtonPermisos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermisos1ActionPerformed(evt);
            }
        });

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitulo1.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jButtonApi1.setText("Clave API");
        jButtonApi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApi1ActionPerformed(evt);
            }
        });

        jLabelAgregarTitulo.setText("Agregar Titulo");

        jTextFieldAgregarTitulo.setText("Opcional");
        jTextFieldAgregarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgregarTituloActionPerformed(evt);
            }
        });

        jLabelPreguntaModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaModificar.setText("¿Desea modificar algún dato más? (Se aplicará a todo");

        jLabelTipoContenido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenido.setText("tipoContenido");

        jLabelPreguntaMotificar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaMotificar2.setText(")");

        jLabelAgregarDescripcion.setText("Agregar descripción");

        jTextFieldAgregarDescripcion.setText("Opcional");

        jLabelAgregarEtiquetas.setText("Agregar etiquetas");

        jTextFieldAgregarEtiquetas.setText("Separar etiquetas con espacios");

        jLabelAgregarPersonas.setText("Agregar personas");

        jTextFieldAgregarPersonas.setText("Escribir nombre o dirección de correo electrónico");

        jLabel1.setText("Licencias");

        buttonGroupLicencia.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setText("Ninguno (Todos los derechos reservados)");

        buttonGroupLicencia.add(jRadioButtonPublicDomainWork);
        jRadioButtonPublicDomainWork.setText("Public Domain Work");

        buttonGroupLicencia.add(jRadioButtonPublicDomainDedication);
        jRadioButtonPublicDomainDedication.setText("Public Domain Dedication (CC0)");
        jRadioButtonPublicDomainDedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPublicDomainDedicationActionPerformed(evt);
            }
        });

        buttonGroupLicencia.add(jRadioButtonNoComercialCompartir);
        jRadioButtonNoComercialCompartir.setText("Atribución-No comercial-Compartir bajo la misma licencia de Creative Commons");

        buttonGroupLicencia.add(jRadioButtonNoComercialCreative);
        jRadioButtonNoComercialCreative.setText("Atribución-No comercial de Creative Commons");

        buttonGroupLicencia.add(jRadioButtonCreativeCommons);
        jRadioButtonCreativeCommons.setText("Creative Commons Atribución-No Comercial - No Derivs");
        jRadioButtonCreativeCommons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreativeCommonsActionPerformed(evt);
            }
        });

        buttonGroupLicencia.add(jRadioButtonAtribucionCreativeCommons);
        jRadioButtonAtribucionCreativeCommons.setText("Atribución de Creative Commons");

        buttonGroupLicencia.add(jRadioButtonCompartirCreativeCommons);
        jRadioButtonCompartirCreativeCommons.setText("Atribución-Compartir bajo la misma licencia de Creative Commons");

        buttonGroupLicencia.add(jRadioButtonNoDerivada);
        jRadioButtonNoDerivada.setText("Atribución-No derivadas de Creative Commons");

        jButtonFinalizar.setText("Finalizar");

        javax.swing.GroupLayout jPanelOpcionalLayout = new javax.swing.GroupLayout(jPanelOpcional);
        jPanelOpcional.setLayout(jPanelOpcionalLayout);
        jPanelOpcionalLayout.setHorizontalGroup(
            jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                        .addComponent(jLabelPreguntaModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipoContenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPreguntaMotificar2))
                    .addComponent(jLabelTitulo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButtonApi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPermisos1)
                .addGap(33, 33, 33))
            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                        .addComponent(jLabelAgregarTitulo)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldAgregarTitulo))
                    .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addComponent(jLabelAgregarEtiquetas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAgregarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionalLayout.createSequentialGroup()
                                .addComponent(jLabelAgregarPersonas)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAgregarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addComponent(jLabelAgregarDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonFinalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonPublicDomainWork)
                    .addComponent(jRadioButtonPublicDomainDedication)
                    .addComponent(jRadioButtonNinguno)
                    .addComponent(jRadioButtonNoComercialCompartir)
                    .addComponent(jRadioButtonCreativeCommons)
                    .addComponent(jRadioButtonNoDerivada)
                    .addComponent(jRadioButtonCompartirCreativeCommons)
                    .addComponent(jRadioButtonAtribucionCreativeCommons)
                    .addComponent(jRadioButtonNoComercialCreative)))
        );
        jPanelOpcionalLayout.setVerticalGroup(
            jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo1)
                    .addComponent(jButtonApi1)
                    .addComponent(jButtonPermisos1))
                .addGap(13, 13, 13)
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreguntaModificar)
                    .addComponent(jLabelTipoContenido)
                    .addComponent(jLabelPreguntaMotificar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionalLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jRadioButtonCreativeCommons)
                        .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAtribucionCreativeCommons)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonCompartirCreativeCommons)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonNoDerivada)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addComponent(jRadioButtonNinguno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPublicDomainWork)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPublicDomainDedication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNoComercialCompartir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNoComercialCreative))
                            .addGroup(jPanelOpcionalLayout.createSequentialGroup()
                                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAgregarTitulo)
                                    .addComponent(jTextFieldAgregarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAgregarDescripcion)
                                    .addComponent(jTextFieldAgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAgregarEtiquetas)
                                    .addComponent(jTextFieldAgregarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAgregarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAgregarPersonas))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jLayeredPaneOpcionalLayout = new javax.swing.GroupLayout(jLayeredPaneOpcional);
        jLayeredPaneOpcional.setLayout(jLayeredPaneOpcionalLayout);
        jLayeredPaneOpcionalLayout.setHorizontalGroup(
            jLayeredPaneOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOpcionalLayout.createSequentialGroup()
                .addComponent(jPanelOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneOpcionalLayout.setVerticalGroup(
            jLayeredPaneOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOpcionalLayout.createSequentialGroup()
                .addComponent(jPanelOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneOpcional.setLayer(jPanelOpcional, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneAlbum.setAlignmentX(0.0F);
        jLayeredPaneAlbum.setAlignmentY(0.0F);
        jLayeredPaneAlbum.setAutoscrolls(true);
        jLayeredPaneAlbum.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneAlbum.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneAlbum.setOpaque(true);

        jPanelAlbum.setAlignmentX(0.0F);
        jPanelAlbum.setAlignmentY(0.0F);
        jPanelAlbum.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelAlbum.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelAlbum.setPreferredSize(new java.awt.Dimension(800, 330));

        jLabelTituloAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTituloAlbum.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jButtonApiAlbum.setText("Clave API");
        jButtonApiAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApiAlbumActionPerformed(evt);
            }
        });

        jButtonPermisosAlbum.setText("Permisos");
        jButtonPermisosAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermisosAlbumActionPerformed(evt);
            }
        });

        jLabelPreguntaAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaAlbum.setText("¿Desea añadir estas");

        jLabelTipoContenidoAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenidoAlbum.setText("tipoContenido");

        jLabelPreguntaAlbum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaAlbum2.setText("a un album?");

        buttonGroupAlbum.add(jRadioButtonSiAlbum);
        jRadioButtonSiAlbum.setText("Si");
        jRadioButtonSiAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiAlbumActionPerformed(evt);
            }
        });

        buttonGroupAlbum.add(jRadioButtonNoAlbum);
        jRadioButtonNoAlbum.setText("No");

        jLabelNombreAlbum.setText("Título del Album:");

        jTextFieldTituloAlbum.setText("carpetaSeleccionada");

        jLabelDescripcionAlbum.setText("Descripción del Album:");

        jTextAreaDescripcionAlbum.setColumns(20);
        jTextAreaDescripcionAlbum.setRows(5);
        jScrollPaneDescripcionAlbum.setViewportView(jTextAreaDescripcionAlbum);

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlbumLayout = new javax.swing.GroupLayout(jPanelAlbum);
        jPanelAlbum.setLayout(jPanelAlbumLayout);
        jPanelAlbumLayout.setHorizontalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlbumLayout.createSequentialGroup()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jRadioButtonSiAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNoAlbum)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelTituloAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButtonApiAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPermisosAlbum)))
                .addGap(24, 24, 24))
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabelPreguntaAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipoContenidoAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPreguntaAlbum2))
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDescripcionAlbum)
                            .addComponent(jLabelNombreAlbum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTituloAlbum)
                            .addComponent(jScrollPaneDescripcionAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlbumLayout.setVerticalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloAlbum)
                    .addComponent(jButtonApiAlbum)
                    .addComponent(jButtonPermisosAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreguntaAlbum)
                    .addComponent(jLabelTipoContenidoAlbum)
                    .addComponent(jLabelPreguntaAlbum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSiAlbum)
                    .addComponent(jRadioButtonNoAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreAlbum)
                    .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneDescripcionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelDescripcionAlbum)))
                .addGap(18, 18, 18)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneAlbumLayout = new javax.swing.GroupLayout(jLayeredPaneAlbum);
        jLayeredPaneAlbum.setLayout(jLayeredPaneAlbumLayout);
        jLayeredPaneAlbumLayout.setHorizontalGroup(
            jLayeredPaneAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAlbumLayout.createSequentialGroup()
                .addComponent(jPanelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneAlbumLayout.setVerticalGroup(
            jLayeredPaneAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAlbumLayout.createSequentialGroup()
                .addComponent(jPanelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneAlbum.setLayer(jPanelAlbum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneGrupos.setAlignmentX(0.0F);
        jLayeredPaneGrupos.setAlignmentY(0.0F);
        jLayeredPaneGrupos.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneGrupos.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneGrupos.setOpaque(true);

        jPanelGrupos.setAlignmentX(0.0F);
        jPanelGrupos.setAlignmentY(0.0F);
        jPanelGrupos.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelGrupos.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelGrupos.setPreferredSize(new java.awt.Dimension(800, 330));

        jButtonApiGrupos.setText("Clave API");
        jButtonApiGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApiGruposActionPerformed(evt);
            }
        });

        jButtonPermisosGrupos.setText("Permisos");
        jButtonPermisosGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermisosGruposActionPerformed(evt);
            }
        });

        jLabelTituloGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTituloGrupos.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jLabelPreguntaGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaGrupos.setText("¿Desea añadir estas");

        jLabelTipoContenidoGrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoContenidoGrupos.setText("tipoContenido");

        jLabelPreguntaGrupos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPreguntaGrupos2.setText("a un mural (pool) de un grupo?");

        buttonGroupGrupos.add(jRadioButtonSiGrupos);
        jRadioButtonSiGrupos.setText("Si");
        jRadioButtonSiGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiGruposActionPerformed(evt);
            }
        });

        buttonGroupGrupos.add(jRadioButtonNoGrupos);
        jRadioButtonNoGrupos.setText("No");

        jListGrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneGrupos.setViewportView(jListGrupos);

        jButtonContinuarGrupos.setText("Continuar");

        javax.swing.GroupLayout jPanelGruposLayout = new javax.swing.GroupLayout(jPanelGrupos);
        jPanelGrupos.setLayout(jPanelGruposLayout);
        jPanelGruposLayout.setHorizontalGroup(
            jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGruposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSiGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNoGrupos)
                .addGap(356, 356, 356))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGruposLayout.createSequentialGroup()
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGruposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonContinuarGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelGruposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneGrupos))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGruposLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelGruposLayout.createSequentialGroup()
                                .addComponent(jLabelPreguntaGrupos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTipoContenidoGrupos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPreguntaGrupos2))
                            .addComponent(jLabelTituloGrupos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButtonApiGrupos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPermisosGrupos)))
                .addGap(25, 25, 25))
        );
        jPanelGruposLayout.setVerticalGroup(
            jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloGrupos)
                    .addComponent(jButtonApiGrupos)
                    .addComponent(jButtonPermisosGrupos))
                .addGap(18, 18, 18)
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreguntaGrupos)
                    .addComponent(jLabelTipoContenidoGrupos)
                    .addComponent(jLabelPreguntaGrupos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSiGrupos)
                    .addComponent(jRadioButtonNoGrupos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinuarGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneGruposLayout = new javax.swing.GroupLayout(jLayeredPaneGrupos);
        jLayeredPaneGrupos.setLayout(jLayeredPaneGruposLayout);
        jLayeredPaneGruposLayout.setHorizontalGroup(
            jLayeredPaneGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneGruposLayout.createSequentialGroup()
                .addComponent(jPanelGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );
        jLayeredPaneGruposLayout.setVerticalGroup(
            jLayeredPaneGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneGruposLayout.createSequentialGroup()
                .addComponent(jPanelGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        jLayeredPaneGrupos.setLayer(jPanelGrupos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneSubir.setAlignmentX(0.0F);
        jLayeredPaneSubir.setAlignmentY(0.0F);
        jLayeredPaneSubir.setEnabled(false);
        jLayeredPaneSubir.setMaximumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneSubir.setMinimumSize(new java.awt.Dimension(800, 330));
        jLayeredPaneSubir.setOpaque(true);

        jPanelSubir.setAlignmentX(0.0F);
        jPanelSubir.setAlignmentY(0.0F);
        jPanelSubir.setMaximumSize(new java.awt.Dimension(800, 330));
        jPanelSubir.setMinimumSize(new java.awt.Dimension(800, 330));
        jPanelSubir.setPreferredSize(new java.awt.Dimension(800, 330));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitulo.setText("Flickr Folder Uploader - Práctica Sistemas Distribuidos 2 - Luis León, Paula Álvarez y Sergio Valero");

        jButtonApi.setText("Clave API");
        jButtonApi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApiActionPerformed(evt);
            }
        });

        jButtonPermisos.setText("Permisos");
        jButtonPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermisosActionPerformed(evt);
            }
        });

        jButtonElegir.setText("Elegir Carpeta a Subir");
        jButtonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElegirActionPerformed(evt);
            }
        });

        jLabelRuta.setText("Ruta Elegida");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipo.setText("Tipo de Contenido");

        buttonGroupTipo.add(jRadioButtonFoto);
        jRadioButtonFoto.setText("Foto");
        jRadioButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFotoActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonCaptura);
        jRadioButtonCaptura.setText("Captura de Pantalla");

        buttonGroupTipo.add(jRadioButtonArte);
        jRadioButtonArte.setText("Arte/Ilustracción");

        jLabelPrivacidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrivacidad.setText("Privacidad");

        jLabelPrivacidadElegida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrivacidadElegida.setForeground(java.awt.Color.red);
        jLabelPrivacidadElegida.setText("Sólo visible para ti");

        jRadioButtonPrivado.setText("Sólo Tú (privado)");

        buttonGroupPrivacidadPrivado.add(jCheckBoxAmigos);
        jCheckBoxAmigos.setText("Tus Amigos");

        buttonGroupPrivacidadPrivado.add(jCheckBoxFamiliares);
        jCheckBoxFamiliares.setText("Tus Familiares");

        jRadioButtonPublico.setText("Cualquier Persona (público)");

        jLabelSeguridad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSeguridad.setText("Seguridad");

        jRadioButtonSegura.setText("Segura");
        jRadioButtonSegura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeguraActionPerformed(evt);
            }
        });

        jRadioButtonModerada.setText("Moderada");

        jRadioButtonRestringida.setText("Restringida");

        jButtonSubir.setText("Confirmar y Subir");
        jButtonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubirLayout = new javax.swing.GroupLayout(jPanelSubir);
        jPanelSubir.setLayout(jPanelSubirLayout);
        jPanelSubirLayout.setHorizontalGroup(
            jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonElegir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonFoto)
                            .addComponent(jLabelTipo)
                            .addComponent(jRadioButtonCaptura)
                            .addComponent(jRadioButtonArte))
                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSubirLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                                        .addComponent(jLabelPrivacidadElegida)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRuta)
                                            .addGroup(jPanelSubirLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabelPrivacidad)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelSeguridad)))
                                .addGap(45, 45, 45))
                            .addGroup(jPanelSubirLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxFamiliares)
                                            .addComponent(jCheckBoxAmigos)))
                                    .addComponent(jRadioButtonPublico)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubirLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonPrivado)
                                        .addGap(49, 49, 49)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSegura)
                                    .addComponent(jRadioButtonModerada)
                                    .addComponent(jRadioButtonRestringida))
                                .addGap(39, 39, 39))))
                    .addComponent(jButtonSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButtonApi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPermisos)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        jPanelSubirLayout.setVerticalGroup(
            jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabelSeguridad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSegura)
                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSubirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonFoto)
                                    .addComponent(jLabelPrivacidadElegida))
                                .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonCaptura)
                                            .addComponent(jRadioButtonPrivado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonArte))
                                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jCheckBoxAmigos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxFamiliares)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPublico))))
                            .addGroup(jPanelSubirLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jRadioButtonModerada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonRestringida))))
                    .addGroup(jPanelSubirLayout.createSequentialGroup()
                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitulo)
                            .addComponent(jButtonApi)
                            .addComponent(jButtonPermisos))
                        .addGap(105, 105, 105)
                        .addComponent(jButtonElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRuta)
                        .addGap(11, 11, 11)
                        .addGroup(jPanelSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabelPrivacidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneSubirLayout = new javax.swing.GroupLayout(jLayeredPaneSubir);
        jLayeredPaneSubir.setLayout(jLayeredPaneSubirLayout);
        jLayeredPaneSubirLayout.setHorizontalGroup(
            jLayeredPaneSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSubirLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPaneSubirLayout.setVerticalGroup(
            jLayeredPaneSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSubirLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPaneSubir.setLayer(jPanelSubir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPaneSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApiActionPerformed

    private void jButtonPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPermisosActionPerformed

    private void jButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonElegirActionPerformed

    private void jRadioButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFotoActionPerformed

    private void jRadioButtonSeguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSeguraActionPerformed

    private void jButtonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubirActionPerformed

    private void jButtonApiAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApiAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApiAlbumActionPerformed

    private void jButtonPermisosAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermisosAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPermisosAlbumActionPerformed

    private void jRadioButtonSiAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSiAlbumActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonApiGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApiGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApiGruposActionPerformed

    private void jButtonPermisosGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermisosGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPermisosGruposActionPerformed

    private void jRadioButtonSiGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSiGruposActionPerformed

    private void jButtonApi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApi1ActionPerformed

    private void jButtonPermisos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermisos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPermisos1ActionPerformed

    private void jTextFieldAgregarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgregarTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgregarTituloActionPerformed

    private void jRadioButtonPublicDomainDedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPublicDomainDedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPublicDomainDedicationActionPerformed

    private void jRadioButtonCreativeCommonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreativeCommonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCreativeCommonsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practiaSD2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practiaSD2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practiaSD2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practiaSD2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practiaSD2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlbum;
    private javax.swing.ButtonGroup buttonGroupGrupos;
    private javax.swing.ButtonGroup buttonGroupLicencia;
    private javax.swing.ButtonGroup buttonGroupPrivacidad;
    private javax.swing.ButtonGroup buttonGroupPrivacidadPrivado;
    private javax.swing.ButtonGroup buttonGroupSeguridad;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonApi;
    private javax.swing.JButton jButtonApi1;
    private javax.swing.JButton jButtonApiAlbum;
    private javax.swing.JButton jButtonApiGrupos;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonContinuarGrupos;
    private javax.swing.JButton jButtonElegir;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonPermisos;
    private javax.swing.JButton jButtonPermisos1;
    private javax.swing.JButton jButtonPermisosAlbum;
    private javax.swing.JButton jButtonPermisosGrupos;
    private javax.swing.JButton jButtonSubir;
    private javax.swing.JCheckBox jCheckBoxAmigos;
    private javax.swing.JCheckBox jCheckBoxFamiliares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgregarDescripcion;
    private javax.swing.JLabel jLabelAgregarEtiquetas;
    private javax.swing.JLabel jLabelAgregarPersonas;
    private javax.swing.JLabel jLabelAgregarTitulo;
    private javax.swing.JLabel jLabelDescripcionAlbum;
    private javax.swing.JLabel jLabelNombreAlbum;
    private javax.swing.JLabel jLabelPreguntaAlbum;
    private javax.swing.JLabel jLabelPreguntaAlbum2;
    private javax.swing.JLabel jLabelPreguntaGrupos;
    private javax.swing.JLabel jLabelPreguntaGrupos2;
    private javax.swing.JLabel jLabelPreguntaModificar;
    private javax.swing.JLabel jLabelPreguntaMotificar2;
    private javax.swing.JLabel jLabelPrivacidad;
    private javax.swing.JLabel jLabelPrivacidadElegida;
    private javax.swing.JLabel jLabelRuta;
    private javax.swing.JLabel jLabelSeguridad;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoContenido;
    private javax.swing.JLabel jLabelTipoContenidoAlbum;
    private javax.swing.JLabel jLabelTipoContenidoGrupos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTituloAlbum;
    private javax.swing.JLabel jLabelTituloGrupos;
    private javax.swing.JLayeredPane jLayeredPaneAlbum;
    private javax.swing.JLayeredPane jLayeredPaneGrupos;
    private javax.swing.JLayeredPane jLayeredPaneOpcional;
    private javax.swing.JLayeredPane jLayeredPaneSubir;
    private javax.swing.JList jListGrupos;
    private javax.swing.JPanel jPanelAlbum;
    private javax.swing.JPanel jPanelGrupos;
    private javax.swing.JPanel jPanelOpcional;
    private javax.swing.JPanel jPanelSubir;
    private javax.swing.JRadioButton jRadioButtonArte;
    private javax.swing.JRadioButton jRadioButtonAtribucionCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonCaptura;
    private javax.swing.JRadioButton jRadioButtonCompartirCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonCreativeCommons;
    private javax.swing.JRadioButton jRadioButtonFoto;
    private javax.swing.JRadioButton jRadioButtonModerada;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonNoAlbum;
    private javax.swing.JRadioButton jRadioButtonNoComercialCompartir;
    private javax.swing.JRadioButton jRadioButtonNoComercialCreative;
    private javax.swing.JRadioButton jRadioButtonNoDerivada;
    private javax.swing.JRadioButton jRadioButtonNoGrupos;
    private javax.swing.JRadioButton jRadioButtonPrivado;
    private javax.swing.JRadioButton jRadioButtonPublicDomainDedication;
    private javax.swing.JRadioButton jRadioButtonPublicDomainWork;
    private javax.swing.JRadioButton jRadioButtonPublico;
    private javax.swing.JRadioButton jRadioButtonRestringida;
    private javax.swing.JRadioButton jRadioButtonSegura;
    private javax.swing.JRadioButton jRadioButtonSiAlbum;
    private javax.swing.JRadioButton jRadioButtonSiGrupos;
    private javax.swing.JScrollPane jScrollPaneDescripcionAlbum;
    private javax.swing.JScrollPane jScrollPaneGrupos;
    private javax.swing.JTextArea jTextAreaDescripcionAlbum;
    private javax.swing.JTextField jTextFieldAgregarDescripcion;
    private javax.swing.JTextField jTextFieldAgregarEtiquetas;
    private javax.swing.JTextField jTextFieldAgregarPersonas;
    private javax.swing.JTextField jTextFieldAgregarTitulo;
    private javax.swing.JTextField jTextFieldTituloAlbum;
    // End of variables declaration//GEN-END:variables
}
